### ISSUE TITLE
Unable to create new accounts in mainnet/testnet with Java SDK only due to INSUFFICIENT_TX_FEE

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-sdk-java#1230]
### Description

At 6:12 AM Wednesday November 9 EST we received a Google alert for Wallawallet in production that new accounts are failing due to INSUFFICIENT_TX_FEE, yet more than 1300 HBAR exists in our account creation fee account. This started happening for each brand new account created using our server-side call, all written in Java. (So this affects all our new users who are creating their one free account.)

In production we use this sdk (as part of a spring-boot app - note that this is "sdk-full" when attempting to reproduce):

`implementation 'com.hedera.hashgraph:sdk-full:2.16.0'`

In my development environment, the same problem has been seen with this SDK:

`implementation 'com.hedera.hashgraph:sdk-full:2.18.1'`

The problem exists both on mainnet and testnet:

Mainnet (not our main fee account, but one we use for diagnosing issues):

```
com.hedera.hashgraph.sdk.ReceiptStatusException: receipt for transaction 0.0.58512@1668004261.474572865 raised status INSUFFICIENT_TX_FEE
	at com.hedera.hashgraph.sdk.TransactionResponse.getReceipt(TransactionResponse.java:86)

```

Testnet:

```
com.hedera.hashgraph.sdk.ReceiptStatusException: receipt for transaction 0.0.55224@1668009471.779737072 raised status INSUFFICIENT_TX_FEE
	at com.hedera.hashgraph.sdk.TransactionResponse.getReceipt(TransactionResponse.java:86)
```

Our code has been running flawlessly in production for a long time and this problem just showed up early this morning. We will need to post a message in our app to make our new users aware. 

### Steps to reproduce

1. Modify your gradle build file in a spring boot application to include: implementation 'com.hedera.hashgraph:sdk-full:2.16.0'
2. Write code similar to this for creating a new account: `        TransactionResponse transactionResponse = new AccountCreateTransaction()
            .setKey(newAccountPublicKey)
            .setInitialBalance(Hbar.fromTinybars(0))
            .setMaxAutomaticTokenAssociations(0)
            .execute(client);
        TransactionReceipt receipt = transactionResponse.getReceipt(client);`
3. Run the code.

### Hedera network

mainnet, testnet

### Version

'com.hedera.hashgraph:sdk-full:2.16.0'

### Operating system

macOS

**Comment by robkainz** [comment]
I just hardcoded the max transaction fee to 5 hbar and it worked, so closing this and will push a new build.
