### ISSUE TITLE
Runtime Exception is thrown while submitting messages to the topic

### ISSUE THREAD

**Issue by thenswan** [hashgraph/hedera-sdk-java#1481]
### Description

`TopicMessageSubmitTransaction` is throwing runtime exception when submitting messages to the topic  on `previewnet`, while using `io.grpc:grpc-okhttp:1.56.1` dependency.

### Steps to reproduce

1. Create empty project following [README.md](https://github.com/hashgraph/hedera-sdk-java/blob/develop/README.md).
  1.1. Use `io.grpc:grpc-okhttp:1.56.1` dependency for gRPC implementation.
  1.2. Enable logs by using `org.slf4j:slf4j-simple:2.0.3` SLF4J implementation.
2. Get previewnet credentials at [Hedera Portal](https://portal.hedera.com/).
3. Paste into MCVE code below previewnet credentials for submitting messages to the topic and run the code.

```
public class GrpcIssueSample {
    public static void main(String[] args) {
        final var accountId = AccountId.fromString("0.0.0");
        final var privateKey = PrivateKey.fromString(
                "000....");

        try (var client = Client
                .forName("previewnet")
                .setOperator(accountId, privateKey)
                .setLogger(new Logger(LogLevel.DEBUG))
                .setCloseTimeout(Duration.of(5, ChronoUnit.SECONDS))) {
            final var submitPrivateKey = PrivateKey.generateECDSA();

            var topicId = new TopicCreateTransaction()
                    .setTransactionMemo("Book Catalog: Creating topic")
                    .setTopicMemo("Topic memo")
                    .setSubmitKey(submitPrivateKey)
                    .execute(client)
                    .getReceipt(client)
                    .topicId;
            assert topicId != null;

            for (int i = 0; i < 10; i++) {
                final var transaction = new TopicMessageSubmitTransaction()
                        .setTransactionMemo("Book Catalog: submitting book identifiers")
                        .setTopicId(topicId)
                        .setMessage("message" + i)
                        .freezeWith(client)
                        .sign(submitPrivateKey);
                final var txResponse = transaction.execute(client);
                final var txReceipt = txResponse.getReceipt(client);
                assert txReceipt.transactionId != null;
                final var txRecord = new TransactionRecordQuery()
                        .setTransactionId(txReceipt.transactionId)
                        .execute(client);
                System.out.println(i + " " + txRecord);
            }
            System.out.println("closing client");
            client.close();
            System.out.println("closed");
        } catch (TimeoutException | PrecheckStatusException | ReceiptStatusException e) {
            System.out.println(e.getMessage());
        }
    }
}
```

### Additional context

```
[hedera-sdk-1] ERROR com.hedera.hashgraph.sdk.AddressBookQuery - Error attempting to get address book at FileId 0.0.102
io.grpc.StatusRuntimeException: UNKNOWN: Unknown error
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[hedera-sdk-1] WARN com.hedera.hashgraph.sdk.logger.Logger - Failed to update address book via mirror node query 
java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNKNOWN: Unknown error
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.hedera.hashgraph.sdk.AddressBookQuery$1.onError(AddressBookQuery.java:243)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Unknown error
	at io.grpc.Status.asRuntimeException(Status.java:539)
	... 13 more
```

### Hedera network

previewnet

### Version

2.25.0

### Operating system

None

**Comment by david-bakin-sl** [comment]
I also saw this though it seemed to appear at close - see [internal slack link](https://swirldslabs.slack.com/archives/C0453UVBR42/p1688767215316199?thread_ts=1688436234.010989&cid=C0453UVBR42)

**Comment by thenswan** [comment]
@david-bakin-sl can you please try to reproduce it again, please? For me it seems like the issue is gone due to Hedera update.
