### ISSUE TITLE
Solidity require statement not throwing errors on hedera 

### ISSUE THREAD

**Issue by rahul-ki** [hashgraph/hedera-sdk-java#156]
I slightly modified the `stateful.sol` used in examples to include a `onlyOwner` modifier (i.e. 
require that only owner can call `set_message()`. 
Then in the `CreateStatefulContract.java`, I called `set_message` from a different account (i.e. not the one that deployed the contract). Although the message doesn't change, there are no errors thrown by the smart contract or Hedera (I tried catching `HederaException` and `HederaNetworkException`).

I have attached the `CreateStatefulContract.java` and the output of my console for reference. 

 `Stateful.sol` that I am working with:
```
pragma solidity >=0.4.22 <0.6.0;

contract StatefulContract {
    // the contract's owner, set in the constructor
    address public owner;

    // the message we're storing
    uint private _message;
    
    modifier onlyOwner {
        require(msg.sender == owner);
        _;
    }

    constructor(uint message_) public {
        // set the owner of the contract for `kill()`
        owner = msg.sender;
        _message = message_;
    }

    function set_message(uint message_) public onlyOwner {
        // only allow the owner to update the message
        _message = message_;
    }

    // return a string
    function get_message() public view returns (uint) {
        return _message;
    }
}
```

CONSOLE OUTPUT:
```
contract bytecode file: 0.0.21691
new contract ID: 0.0.21692
contract returned message: 1234
Calling set_message from new client.
Waiting 5s for consensus and contract execution
Calling get_message again to see if changes occurred.
contract returned message: 1234
```

[CreateStatefulContract.java.txt](https://github.com/hashgraph/hedera-sdk-java/files/3339483/CreateStatefulContract.java.txt)

**Comment by gregscullard** [comment]
Is `modifier onlyOwner` supported in solidity 4.25 ? Which compiler version did you use ?
It's possible this is hedera and not sdk related if the modifier isn't supported in 4.25.

Do you get an error if you include the require in the `set_message` ?

**Comment by rahul-ki** [comment]
Not getting an error both ways i.e. having require within `set_message` and having the modifier on the function definition.

**Comment by mehcode** [comment]
Just for a sanity check, we don't compile from the sol in the SDK. You need to compile with like Remix first.

**Comment by rahul-ki** [comment]
Ofcourse haha. I mentioned the byetcode in the java file. Been coding on Hashgraph since October last year.

**Comment by gregscullard** [comment]
@rahul-ki I wonder if the call succeeds from the transaction point of view (there was nothing wrong with it), but the result of the function call (found in the record for the call) may indicate the call responded with a require condition that wasn't met.
Can you try again, this time getting a record for the call (executeForRecord) and inspect the contents of the record. 

something along the lines of
```
        var res = new ContractExecuteTransaction(client).setContractId(newContractId)
            .setGas(100_000_000)
            .setFunctionParameters(CallParams.function("set_message")
                .addString("hello from hedera again!"))
            .executeForRecord();
        
        System.out.println(res.getCallResult().getErrorMessage());
```

**Comment by gregscullard** [comment]
if you're running the call as a local call
```
        var contractCallResult = new ContractCallQuery(client).setContractId(newContractId)
            .setGas(100_000_000)
            .setFunctionParameters(CallParams.function("get_message"))
            .execute();
        
        if (contractCallResult.getErrorMessage() != null) {
            System.out.println("error calling contract: " + contractCallResult.getErrorMessage());
            return;
        }
```

`contractCallResult.getErrorMessage()` may contain the error raised by the contract method.

**Comment by gregscullard** [comment]
@rahul-ki the SDK and Hedera work as expected.

* .execute() is a fire and forget statement, it sends the transaction to Hedera but does not wait for a result. As a result, it cannot return an exception since it doesn't know the result of the call other than it has been accepted by the node and been sent for consensus.
* .executeForReceipt() and executeForRecord() on the other hand send the transaction to Hedera and wait for a response by polling for a receipt or record.

If you compile your contract as you have it with the onlyOwner clause, and run the contract function from your java code with either executeForReceipt or executeForRecord, you will get an exception raised. See below.

Java Code
```
package com.hedera.hashgraph.sdk.examples.advanced;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.hedera.hashgraph.sdk.CallParams;
import com.hedera.hashgraph.sdk.HederaException;
import com.hedera.hashgraph.sdk.contract.ContractCallQuery;
import com.hedera.hashgraph.sdk.contract.ContractCreateTransaction;
import com.hedera.hashgraph.sdk.contract.ContractExecuteTransaction;
import com.hedera.hashgraph.sdk.examples.ExampleHelper;
import com.hedera.hashgraph.sdk.file.FileCreateTransaction;

import java.io.IOException;
import java.io.InputStreamReader;
import java.time.Duration;
import java.time.Instant;

public final class CreateStatefulContract {
    private CreateStatefulContract() { }

    public static void main(String[] args) throws HederaException, IOException, InterruptedException {
        var cl = CreateStatefulContract.class.getClassLoader();

        var gson = new Gson();

        JsonObject jsonObject;

        try (var jsonStream = cl.getResourceAsStream("stateful.json")) {
            if (jsonStream == null) {
                throw new RuntimeException("failed to get stateful.json");
            }

            jsonObject = gson.fromJson(new InputStreamReader(jsonStream), JsonObject.class);
        }

        var byteCodeHex = jsonObject.getAsJsonPrimitive("object")
            .getAsString();
        var byteCode = byteCodeHex.getBytes();

        var operatorKey = ExampleHelper.getOperatorKey();
        var client = ExampleHelper.createHederaClient();

        // create the contract's bytecode file
        var fileTx = new FileCreateTransaction(client).setExpirationTime(
            Instant.now()
                .plus(Duration.ofSeconds(2592000)))
            // Use the same key as the operator to "own" this file
            .addKey(operatorKey.getPublicKey())
            .setContents(byteCode);

        var fileReceipt = fileTx.executeForReceipt();
        var newFileId = fileReceipt.getFileId();

        System.out.println("contract bytecode file: " + newFileId);

        var contractTx = new ContractCreateTransaction(client).setBytecodeFile(newFileId)
            .setAutoRenewPeriod(Duration.ofHours(1))
            .setGas(100_000_000)
            .setConstructorParams(
                CallParams.constructor()
                    .addString("hello from hedera!"));

        var contractReceipt = contractTx.executeForReceipt();
        var newContractId = contractReceipt.getContractId();

        System.out.println("new contract ID: " + newContractId);

        var contractCallResult = new ContractCallQuery(client).setContractId(newContractId)
            .setGas(100_000_000)
            .setFunctionParameters(CallParams.function("get_message"))
            .execute();

        if (contractCallResult.getErrorMessage() != null) {
            System.out.println("error calling contract: " + contractCallResult.getErrorMessage());
            return;
        }

        var message = contractCallResult.getString(0);
        System.out.println("contract returned message: " + message);

        System.out.println("Calling with fire and forget execute()");
        new ContractExecuteTransaction(client).setContractId(newContractId)
                .setGas(100_000_000)
                .setFunctionParameters(CallParams.function("set_message")
                    .addString("hello from hedera again!"))
                .execute();
        System.out.println("No error");

        System.out.println("Now calling with executeForRecord()");
        var record = new ContractExecuteTransaction(client).setContractId(newContractId)
            .setGas(100_000_000)
            .setFunctionParameters(CallParams.function("set_message")
                .addString("hello from hedera again!"))
            .executeForReceipt();

    }
}
```

Console output
```
contract bytecode file: 0.0.3412
new contract ID: 0.0.3413
contract returned message: hello from hedera!
Calling with fire and forget execute()
No error
Now calling with executeForRecord()
Exception in thread "main" com.hedera.hashgraph.sdk.HederaException: CONTRACT_REVERT_EXECUTED
	at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
	at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:33)
	at com.hedera.hashgraph.sdk.Transaction.executeAndWaitFor(Transaction.java:231)
	at com.hedera.hashgraph.sdk.Transaction.executeForReceipt(Transaction.java:262)
	at com.hedera.hashgraph.sdk.TransactionBuilder.executeForReceipt(TransactionBuilder.java:178)
	at com.hedera.hashgraph.sdk.examples.advanced.CreateStatefulContract.main(CreateStatefulContract.java:94)
```

Closing this issue.
