### ISSUE TITLE
AddressBookQuery throwing java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by aadityapaliwal** [hashgraph/hedera-sdk-java#1566]
### Description

I am using below method to get the nodeAddress but it is throwing an error.

`
fun getNetwork() : NodeAddressBook {
        return AddressBookQuery().setFileId(FileId.ADDRESS_BOOK).execute(Client.forName(networkName))
    }

### Steps to reproduce

1. Use a Dapp.
2. Pair with your wallet.
3. It will call JSONRPCRequest(id=1692618823978090, method=getNetwork, params={"accountId":"0.0.xxxxx"}) for your account.
4. Returning the node account id throwing this.

### Additional context

> FATAL EXCEPTION: DefaultDispatcher-worker-12
                                                                                                    Process: cc.dropp.wallet, PID: 27783
                                                                                                    java.lang.AbstractMethodError: abstract method "java.util.Collection io.grpc.ManagedChannelProvider.getSupportedSocketAddressTypes()"
                                                                                                    	at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:186)
                                                                                                    	at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:155)
                                                                                                    	at io.grpc.Grpc.newChannelBuilder(Grpc.java:101)
                                                                                                    	at com.hedera.hashgraph.sdk.BaseNode.getChannel(BaseNode.java:273)
                                                                                                    	at com.hedera.hashgraph.sdk.AddressBookQuery.buildCall(AddressBookQuery.java:277)
                                                                                                    	at com.hedera.hashgraph.sdk.AddressBookQuery.execute(AddressBookQuery.java:178)
                                                                                                    	at com.hedera.hashgraph.sdk.AddressBookQuery.execute(AddressBookQuery.java:163)
                                                                                                    	at com.opencrowd.drop.common.HederaHashgraphManager.getNetwork(HederaHashgraphManager.kt:49)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity.handleGetNetwork(MainActivity.kt:286)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity.access$handleGetNetwork(MainActivity.kt:45)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity$onStart$walletDelegate$1.onSessionRequest(MainActivity.kt:221)
                                                                                                    	at com.walletconnect.web3.wallet.client.Web3Wallet$setWalletDelegate$signWalletDelegate$1.onSessionRequest(Web3Wallet.kt:43)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invokeSuspend(SignProtocol.kt:60)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:8)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

### Hedera network

testnet

### Version

v2.27.0

### Operating system

macOS

**Comment by thenswan** [comment]
Hey @aadityapaliwal, thank you for raising this issue :)
I checked the details you provided and would like to request MCVE -- could you upload it to the GitHub repo and provide me with a link, please?

**Comment by aadityapaliwal** [comment]
Hi @thenswan 

Here is the repo I have created for you - https://github.com/aadityapaliwal/WalletConnectDemo

I am connecting with this Dapp - https://dropp-walletconnect-testbed.s3.amazonaws.com/

**Comment by thenswan** [comment]
Hi @aadityapaliwal, thank you for providing additional context - I will take a look.

**Comment by thenswan** [comment]
Hi @aadityapaliwal, I resolved this issue. Can you please give me access to the repo, so I can push the branch with a fix?

**Comment by aadityapaliwal** [comment]
@thenswan Given. Please check.

**Comment by thenswan** [comment]
@aadityapaliwal thanks, please check branch --> https://github.com/aadityapaliwal/WalletConnectDemo/tree/1566

**Comment by thenswan** [comment]
@aadityapaliwal awesome, your welcome :)
