### ISSUE TITLE
Getting exception when calling AccountInfoQuery()

### ISSUE THREAD

**Issue by aadityapaliwal** [hashgraph/hedera-sdk-java#1571]
### Description

I am using below method to get the account info but it is throwing an error. I am testing this in Motorola moto g5 device. Use this demo project to repro - https://github.com/aadityapaliwal/WalletConnectDemo

### Steps to reproduce

- Use a Dapp.
- Pair with your wallet.
- From Dapp, use get account info with an account.
- On wallet we will get a request from dapp. To handle that code, I am using below code -

```
fun getClient() : Client {
        val client = Client.forName(networkName)
        client.setOperator(operatorAccountId(), operatorKey())
        return client
    }
    
fun getAccountInfo(bytes: ByteArray) : AccountInfo {
        try {
            val accountID = AccountId.fromBytes(bytes)
            val client = getClient()
            val accountInfo = AccountInfoQuery().setAccountId(accountID).execute(client)
            return accountInfo
        } catch (e: Exception) {

        }
    }
```

- When I am executing query to get the AccountInfo, it's throwing below exception.

### Additional context

FATAL EXCEPTION: DefaultDispatcher-worker-2
                                                                                                    Process: cc.test.sample, PID: 24549
                                                                                                    java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /system/framework/core-oj.jar)
                                                                                                    	at com.hedera.hashgraph.sdk.AccountInfo.fromProtobuf(AccountInfo.java:264)
                                                                                                    	at com.hedera.hashgraph.sdk.AccountInfoQuery.mapResponse(AccountInfoQuery.java:100)
                                                                                                    	at com.hedera.hashgraph.sdk.AccountInfoQuery.mapResponse(AccountInfoQuery.java:37)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable$GrpcRequest.mapResponse(Executable.java:922)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:456)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:364)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.test.sample.common.HederaHashgraphManager.getAccountInfo(HederaHashgraphManager.kt:53)
                                                                                                    	at com.test.sample.ui.MainActivity.handleQueryRequest(MainActivity.kt:246)
                                                                                                    	at com.test.sample.ui.MainActivity.access$handleQueryRequest(MainActivity.kt:35)
                                                                                                    	at com.test.sample.ui.MainActivity$onStart$walletDelegate$1.onSessionRequest(MainActivity.kt:114)
                                                                                                    	at com.walletconnect.web3.wallet.client.Web3Wallet$setWalletDelegate$signWalletDelegate$1.onSessionRequest(Web3Wallet.kt:43)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invokeSuspend(SignProtocol.kt:56)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:8)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### Hedera network

testnet

### Version

v2.27.0

### Operating system

macOS

**Comment by thenswan** [comment]
Hey @aadityapaliwal, thank you for raising this issue :) 
Will check it.

**Comment by aadityapaliwal** [comment]
@thenswan I am using the Motorola Moto G5 Android version 8.1.0 (API Level 27). Please use the below steps to repro it - 

- Navigate to https://dropp-walletconnect-testbed.s3.amazonaws.com/index.html
- Copy the URI from copy to clipboard and send it in your device.
- Connect wallet with URI using Connect Dapp menu on home page and paste the URI.
- It will ask to approve the request and open a page. Tap on Approve.
- As soon as I approve it, I have started getting sessionRequest from Dapp for getNetwork and getMirrorNetwork. getNetwork throws a different error for which I create an issue [here](https://github.com/hashgraph/hedera-sdk-java/issues/1566). You can comment out the handleGetNetworkRequest call onSessionRequest method.
- Now go to above Dapp and choose Get Account Info, enter an account id.
- Now you will get call method for crypto_get_info with this params - JSONRPCRequest(id=1693371007131300, method=call, params={"accountId":"0.0.622648","executable":"Sg4KAhAAEggIABAAGITRIQ==","isTransaction":false})

- It will crash the app and mentioned error has been throw. 

I didn't get your last point - and I would like to point your attention to [this release](https://github.com/hashgraph/hedera-sdk-java/blob/develop/CHANGELOG.md#2250) (what’s changed), so you can double-check versions in your project.

Do you want me downgrade the SDK version?

**Comment by thenswan** [comment]
@aadityapaliwal many thanks for providing additional details 🙂 👍
I am getting an error on this step -- "It will ask to approve the request and open a page. Tap on Approve." (when approving session), which is: `ApproveError` and the error message is `Accounts must be CAIP-10 compliant`. Could you please try to repeat this flow in your repo in order to ensure that it is still working?

Regarding my link to release - for example, there is a note in a changelog that "Minimum supported Android version to 8" (and in your `build.gradle` file, there is a line`minSdkVersion = 24`). I suggest checking dependencies and their versions in the Android example [over here](https://github.com/hashgraph/hedera-sdk-java/tree/develop/example-android) and comparing it with yours in your repo.

**Comment by aadityapaliwal** [comment]
@thenswan Sorry I missed one thing here. Please add your hedera account id, private and public key in the string.xml

  ```
<string name="operator_acc_id"></string>
  <string name="operator_pvt_key"></string>
  <string name="operator_public_key"></string>
```

**Comment by aadityapaliwal** [comment]
@thenswan Any update on this?

We had to go live with our app but in mainnet I am getting one more similar issue - 

```
Fatal Exception: java.lang.NoSuchMethodError: No static method delayedExecutor(JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/Executor; in class Ljava/util/concurrent/CompletableFuture; or its super classes (declaration of 'java.util.concurrent.CompletableFuture' appears in /apex/com.android.art/javalib/core-oj.jar)
       at com.hedera.hashgraph.sdk.Delayer.delayFor(Delayer.java:70)
       at com.hedera.hashgraph.sdk.Client.scheduleNetworkUpdate(Client.java:350)
       at com.hedera.hashgraph.sdk.Client.<init>(Client.java:114)
       at com.hedera.hashgraph.sdk.Client.forMainnet(Client.java:181)
       at com.hedera.hashgraph.sdk.Client.forName(Client.java:163)
       at com.opencrowd.drop.common.HederaHashgraphManager.getClient(HederaHashgraphManager.kt:40)
       at com.opencrowd.drop.common.HederaHashgraphManager.getAccountBalance(HederaHashgraphManager.kt:46)
       at com.opencrowd.drop.ui.MainActivity.handleGetAccountBalanceRequest(MainActivity.kt:417)
       at com.opencrowd.drop.ui.MainActivity.access$handleGetAccountBalanceRequest(MainActivity.kt:59)
       at com.opencrowd.drop.ui.MainActivity$updateWalletConnectDelegates$walletDelegate$1.onSessionRequest(MainActivity.kt:285)
       at com.walletconnect.web3.wallet.client.Web3Wallet$setWalletDelegate$signWalletDelegate$1.onSessionRequest(Web3Wallet.kt:43)
       at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invokeSuspend(SignProtocol.kt:56)
       at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(:8)
       at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(:4)
       at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

In this below code -

```
private fun getClient() : Client {
        val client = Client.forName(networkName)
        client.setOperator(operatorAccountId(), operatorKey())
        return client
    }
```

**Comment by thenswan** [comment]
@aadityapaliwal hey, the fix for this issue is merged and will be available soon with the next release of the Java SDK 🙂

**Comment by aadityapaliwal** [comment]
Thanks @thenswan

**Comment by aadityapaliwal** [comment]
@thenswan I am still facing it. Please check the below crash logs - 

```
FATAL EXCEPTION: DefaultDispatcher-worker-17
                                                                                                    Process: cc.dropp.wallet, PID: 2651
                                                                                                    java.lang.NoSuchMethodError: No virtual method orTimeout(JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/CompletableFuture; in class Ljava/util/concurrent/CompletableFuture; or its super classes (declaration of 'java.util.concurrent.CompletableFuture' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:486)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.executeAsync(Query.java:51)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:475)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.executeAsync(Query.java:51)
                                                                                                    	at com.opencrowd.drop.common.HederaHashgraphManager.getAccountInfo(HederaHashgraphManager.kt:75)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity.handleQueryRequest(MainActivity.kt:505)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity.access$handleQueryRequest(MainActivity.kt:56)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity$updateWalletConnectDelegates$walletDelegate$1.onSessionRequest(MainActivity.kt:360)
                                                                                                    	at com.walletconnect.web3.wallet.client.Web3Wallet$setWalletDelegate$signWalletDelegate$1.onSessionRequest(Web3Wallet.kt:43)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invokeSuspend(SignProtocol.kt:56)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:8)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c3fd3d2, Dispatchers.IO]
```

**Comment by aadityapaliwal** [comment]
@thenswan Is it fixed?

**Comment by thenswan** [comment]
Hi @aadityapaliwal, please check it with Java SDK v2.29.1, it should have Android-related fixes. Let me know if it works for you 🙂

**Comment by aadityapaliwal** [comment]
@thenswan Yeah, I have updated SDK to the latest v2.31.0 and it seems to be working fine. Thanks!
