### ISSUE TITLE
Can't use this repo to get account balance, but the JavaScript SDK works!

### ISSUE THREAD

**Issue by zydjohnHotmail** [hashgraph/hedera-sdk-java#1614]
### Description

Hello:
I am new to this blockchain, but I have quite some experience with other blockchains. I have applied for an acocunt with Hedera blockchain and have some testnet tokens.
Here I can use the following Java code to get my account balance:
package web3.hedrea;

import com.hedera.hashgraph.sdk.Client;
import java.util.concurrent.TimeoutException;
import com.hedera.hashgraph.sdk.AccountBalance;
import com.hedera.hashgraph.sdk.AccountBalanceQuery;
import com.hedera.hashgraph.sdk.AccountId;
import com.hedera.hashgraph.sdk.PrivateKey;
import io.github.cdimascio.dotenv.Dotenv;

public class GetAccountBalance {
  public static void main(String[] args) throws TimeoutException {
    Dotenv dotenv = Dotenv.load();

    String accountIdStr = dotenv.get("ACCOUNT_ID");
    String privateKeyStr = dotenv.get("PRIVATE_KEY");
    String network = dotenv.get("HEDERA_NETWORK");

    AccountId accountId = AccountId.fromString(accountIdStr);
    PrivateKey privateKey = PrivateKey.fromString(privateKeyStr);
    Client client = Client.forName(network);
    client.setOperator(accountId, privateKey);
    AccountBalanceQuery query = new AccountBalanceQuery()
        .setAccountId(accountId);
    try {
      AccountBalance balance = query.execute(client);
      System.out.println("Account Balance: " + balance.hbars + " tinybars");
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      client.close();
    }
  }
}
I am using Maven, the following is the pom.xml file:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <groupId>web3.hedrea</groupId>
 <artifactId>hedera-balance-example</artifactId>
 <packaging>jar</packaging>
 <version>1.0-SNAPSHOT</version>
 <name>hedera-balance-example</name>
 <url>http://maven.apache.org</url>
 <dependencies>
  <dependency>
  <groupId>com.hedera.hashgraph</groupId>
  <artifactId>sdk</artifactId>
  <version>2.29.0</version>
  </dependency>
 <dependency>
  <groupId>io.github.cdimascio</groupId>
  <artifactId>dotenv-java</artifactId>
  <version>3.0.0</version>
 </dependency>   
  <dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-java-api-checker</artifactId>
    <version>1.1.0</version>
  </dependency>
  <dependency>
   <groupId>junit</groupId>
   <artifactId>junit</artifactId>
   <version>3.8.1</version>
   <scope>test</scope>
  </dependency>
 </dependencies>
 <build>
  <plugins>
   <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.11.0</version>
    <configuration>
     <source>17</source>
     <target>17</target>
    </configuration>
   </plugin>
  </plugins>
 </build>
</project>
=> I have installed Java JDK-17, and I use mvn install to install necessary packages.
D:\JavaProjects\hedera-balance-example>type pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>web3.hedrea</groupId>
  <artifactId>hedera-balance-example</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>hedera-balance-example</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
    <groupId>com.hedera.hashgraph</groupId>
    <artifactId>sdk</artifactId>
    <version>2.29.0</version>
    </dependency>
  <dependency>
    <groupId>io.github.cdimascio</groupId>
    <artifactId>dotenv-java</artifactId>
    <version>3.0.0</version>
  </dependency>
    <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-java-api-checker</artifactId>
        <version>1.1.0</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <source>17</source>
          <target>17</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

D:\JavaProjects\hedera-balance-example>mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< web3.hedrea:hedera-balance-example >-----------------
[INFO] Building hedera-balance-example 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ hedera-balance-example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\JavaProjects\hedera-balance-example\src\main\resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ hedera-balance-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ hedera-balance-example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\JavaProjects\hedera-balance-example\src\test\resources
[INFO]
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ hedera-balance-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- surefire:3.1.2:test (default-test) @ hedera-balance-example ---
[INFO] Using auto detected provider org.apache.maven.surefire.junit.JUnit3Provider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running web3.hedrea.AppTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s -- in web3.hedrea.AppTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jar:3.3.0:jar (default-jar) @ hedera-balance-example ---
[INFO] Building jar: D:\JavaProjects\hedera-balance-example\target\hedera-balance-example-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- install:3.1.1:install (default-install) @ hedera-balance-example ---
[INFO] Installing D:\JavaProjects\hedera-balance-example\pom.xml to C:\Users\John\.m2\repository\web3\hedrea\hedera-balance-example\1.0-SNAPSHOT\hedera-balance-example-1.0-SNAPSHOT.pom
[INFO] Installing D:\JavaProjects\hedera-balance-example\target\hedera-balance-example-1.0-SNAPSHOT.jar to C:\Users\John\.m2\repository\web3\hedrea\hedera-balance-example\1.0-SNAPSHOT\hedera-balance-example-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.977 s
[INFO] Finished at: 2023-10-05T22:05:30+02:00
[INFO] ------------------------------------------------------------------------

D:\JavaProjects\hedera-balance-example>
I can compile: 
D:\JavaProjects\hedera-balance-example>mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< web3.hedrea:hedera-balance-example >-----------------
[INFO] Building hedera-balance-example 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ hedera-balance-example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\JavaProjects\hedera-balance-example\src\main\resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ hedera-balance-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.669 s
[INFO] Finished at: 2023-10-05T22:06:17+02:00
[INFO] ------------------------------------------------------------------------

D:\JavaProjects\hedera-balance-example>
=> But when I run this, it failed:
D:\JavaProjects\hedera-balance-example>mvn compile exec:java -Dexec.mainClass="web3.hedrea.GetAccountBalance"
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< web3.hedrea:hedera-balance-example >-----------------
[INFO] Building hedera-balance-example 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ hedera-balance-example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\JavaProjects\hedera-balance-example\src\main\resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ hedera-balance-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec:3.1.0:java (default-cli) @ hedera-balance-example ---
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
        at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
        at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
        at com.hedera.hashgraph.sdk.BaseNode.getChannel(BaseNode.java:279)
        at com.hedera.hashgraph.sdk.BaseNode.channelFailedToConnect(BaseNode.java:306)
        at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:412)
        at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
        at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:364)
        at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
        at web3.hedrea.GetAccountBalance.main(GetAccountBalance.java:26)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
        at java.base/java.lang.Thread.run(Thread.java:833)
[WARNING] thread Thread[Thread-1,5,web3.hedrea.GetAccountBalance] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Thread-1,5,web3.hedrea.GetAccountBalance] will linger despite being asked to die via interruption
[WARNING] NOTE: 1 thread(s) did not finish despite being asked to via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=web3.hedrea.GetAccountBalance,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:803)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:319)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.397 s
[INFO] Finished at: 2023-10-05T22:07:20+02:00
[INFO] ------------------------------------------------------------------------

D:\JavaProjects\hedera-balance-example>

But the funny thing is: for the same .env file in the root folder, I can use JavaScript SDK to get my account balance, here is the JavaScript code ( AccountBalance.js)

import { Wallet, LocalProvider, AccountBalanceQuery } from "@hashgraph/sdk";
import dotenv from "dotenv";
dotenv.config();
async function main() {
if (process.env.ACCOUNT_ID == null || process.env.PRIVATE_KEY == null) {
throw new Error(
"Environment variables ACCOUNT_ID, and PRIVATE_KEY are required."
);
}
const wallet = new Wallet(
process.env.ACCOUNT_ID,
process.env.PRIVATE_KEY,
new LocalProvider()
);
const balance = await new AccountBalanceQuery()
.setAccountId(wallet.getAccountId())
.executeWithSigner(wallet);
console.log(
${wallet .getAccountId() .toString()} balance = ${balance.hbars.toString()}
);
}
void main();
setTimeout(() => {
process.exit(0);
}, 3000);
D:\nodejs\hedra-project>node AccountBalance.js
0.0.4470974 balance = 10000 ℏ
D:\nodejs\hedra-project>
So I have 10000 testnet tokens.
But run the Java code is very tough, never get it working.
I am using Windows 10 (version 23H2). The java information: 
D:\JavaProjects\hedera-balance-example>java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

D:\JavaProjects\hedera-balance-example>
Any suggestions?

### Steps to reproduce

1. mvn archetype:generate -DgroupId=web3.hedrea -DartifactId=hedera-balance-example -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
2. Modify pom.xml to add necessary Java packages.
3. mvn install
4. Change App.java to GetAccountBalance.java and modify the code.
5. mvn compile
6. mvn compile exec:java -Dexec.mainClass="web3.hedrea.GetAccountBalance"

### Additional context

![HederaJavaSDKAccountBalanceNOK](https://github.com/hashgraph/hedera-sdk-java/assets/45263518/bc671834-4584-4e05-ab0e-41982b549f11)

### Hedera network

testnet

### Version

2.29.0

### Operating system

Windows

**Comment by iron4548** [comment]
The solution is in the exception message. Add this to your pom.xml and try again.

```
<!-- https://mvnrepository.com/artifact/io.grpc/grpc-netty -->
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-netty</artifactId>
    <version>1.57.2</version>
</dependency>
```

also to fix the logging error, add

```
<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>2.0.7</version>
    <scope>test</scope>
</dependency>
```

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your reply, I have changed the pom.xml and tried again, but still not working:

D:\JavaProjects\hedera-balance-example>mvn compile exec:java -Dexec.mainClass="web3.hedrea.GetAccountBalance"
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< web3.hedrea:hedera-balance-example >-----------------
[INFO] Building hedera-balance-example 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ hedera-balance-example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\JavaProjects\hedera-balance-example\src\main\resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ hedera-balance-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec:3.1.0:java (default-cli) @ hedera-balance-example ---
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[WARNING]
java.lang.NoClassDefFoundError: io/grpc/InternalGlobalInterceptors
    at io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors (ManagedChannelImplBuilder.java:643)
    at io.grpc.internal.ManagedChannelImplBuilder.build (ManagedChannelImplBuilder.java:631)
    at io.grpc.internal.AbstractManagedChannelImplBuilder.build (AbstractManagedChannelImplBuilder.java:297)
    at com.hedera.hashgraph.sdk.BaseNode.getChannel (BaseNode.java:288)
    at com.hedera.hashgraph.sdk.BaseNode.channelFailedToConnect (BaseNode.java:306)
    at com.hedera.hashgraph.sdk.Executable.execute (Executable.java:412)
    at com.hedera.hashgraph.sdk.Query.execute (Query.java:51)
    at com.hedera.hashgraph.sdk.Executable.execute (Executable.java:364)
    at com.hedera.hashgraph.sdk.Query.execute (Query.java:51)
    at web3.hedrea.GetAccountBalance.main (GetAccountBalance.java:26)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.grpc.InternalGlobalInterceptors
    at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass (URLClassLoaderBuilder.java:198)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:520)
    at io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors (ManagedChannelImplBuilder.java:643)
    at io.grpc.internal.ManagedChannelImplBuilder.build (ManagedChannelImplBuilder.java:631)
    at io.grpc.internal.AbstractManagedChannelImplBuilder.build (AbstractManagedChannelImplBuilder.java:297)
    at com.hedera.hashgraph.sdk.BaseNode.getChannel (BaseNode.java:288)
    at com.hedera.hashgraph.sdk.BaseNode.channelFailedToConnect (BaseNode.java:306)
    at com.hedera.hashgraph.sdk.Executable.execute (Executable.java:412)
    at com.hedera.hashgraph.sdk.Query.execute (Query.java:51)
    at com.hedera.hashgraph.sdk.Executable.execute (Executable.java:364)
    at com.hedera.hashgraph.sdk.Query.execute (Query.java:51)
    at web3.hedrea.GetAccountBalance.main (GetAccountBalance.java:26)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:833)
[WARNING] thread Thread[Thread-1,5,web3.hedrea.GetAccountBalance] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Thread-1,5,web3.hedrea.GetAccountBalance] will linger despite being asked to die via interruption
[WARNING] NOTE: 1 thread(s) did not finish despite being asked to via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=web3.hedrea.GetAccountBalance,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:803)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:319)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.773 s
[INFO] Finished at: 2023-10-06T09:16:19+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default-cli) on project hedera-balance-example: An exception occurred while executing the Java class. io/grpc/InternalGlobalInterceptors: io.grpc.InternalGlobalInterceptors -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

D:\JavaProjects\hedera-balance-example>
The following is the current pom.xml:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>web3.hedrea</groupId>
  <artifactId>hedera-balance-example</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>hedera-balance-example</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
    <groupId>com.hedera.hashgraph</groupId>
    <artifactId>sdk</artifactId>
    <version>2.29.0</version>
    </dependency>
  <dependency>
    <groupId>io.github.cdimascio</groupId>
    <artifactId>dotenv-java</artifactId>
    <version>3.0.0</version>
  </dependency>   
  <dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-netty</artifactId>
    <version>1.57.2</version>
   </dependency> 
    <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-java-api-checker</artifactId>
        <version>1.1.0</version>
    </dependency>
  <dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>2.0.7</version>
    <scope>test</scope>
  </dependency>    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <source>17</source>
          <target>17</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

=> Why it is so difficult to get this working?

**Comment by iron4548** [comment]
Yes, I also find it tricky to get up and going with a Java project too. Javascript / Typescript is definitely a lot easier for new devs to get up and going.

Maybe try adding

```
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-core</artifactId>
    <version>1.57.2</version>
</dependency>
```

To try an address this: "java.lang.NoClassDefFoundError: io/grpc/InternalGlobalInterceptors"

And ensure you run ```mvn clean install``` afterwards.

Btw try and wrap your code in code blocks to make it easier for us to read. It's the < > icon button.

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks, this time, it almost works:
D:\JavaProjects\hedera-balance-example>mvn compile exec:java -Dexec.mainClass="web3.hedrea.GetAccountBalance"
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< web3.hedrea:hedera-balance-example >-----------------
[INFO] Building hedera-balance-example 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ hedera-balance-example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\JavaProjects\hedera-balance-example\src\main\resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ hedera-balance-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec:3.1.0:java (default-cli) @ hedera-balance-example ---
Account Balance: 10000 ? tinybars
Terminate batch job (Y/N)? y

D:\JavaProjects\hedera-balance-example> => But the code seems stuck here. In JavaScript, I can add some timeout to quit after 3 seconds, but I don't know how to do this in Java. I show you the current Java code:
`package web3.hedrea;

import com.hedera.hashgraph.sdk.Client;
import java.util.concurrent.TimeoutException;
import com.hedera.hashgraph.sdk.AccountBalance;
import com.hedera.hashgraph.sdk.AccountBalanceQuery;
import com.hedera.hashgraph.sdk.AccountId;
import com.hedera.hashgraph.sdk.PrivateKey;
import io.github.cdimascio.dotenv.Dotenv;

public class GetAccountBalance {
    public static void main(String[] args) throws TimeoutException {
        Dotenv dotenv = Dotenv.load();

        String accountIdStr = dotenv.get("ACCOUNT_ID");
        String privateKeyStr = dotenv.get("PRIVATE_KEY");
        String network = dotenv.get("HEDERA_NETWORK");

        AccountId accountId = AccountId.fromString(accountIdStr);
        PrivateKey privateKey = PrivateKey.fromString(privateKeyStr);
        Client client = Client.forName(network);
        client.setOperator(accountId, privateKey);
        AccountBalanceQuery query = new AccountBalanceQuery()
                .setAccountId(accountId);
        try {
            AccountBalance balance = query.execute(client);
            System.out.println("Account Balance: " + balance.hbars + " tinybars");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            client.close();
        }
    }
}
`

**Comment by iron4548** [comment]
Glad you got it working.
