### ISSUE TITLE
java.lang.VerifyError - Bad type on operand stack @ NftAllowance.mergeApprovedForAll with reason: "Type 'com/google/protobuf/BoolValue' (current frame, stack[2]) is not assignable to 'com/google/protobuf/GeneratedMessageLite' when using AccountAllowanceApproveTransaction

### ISSUE THREAD

**Issue by iron4548** [hashgraph/hedera-sdk-java#1615]
### Description

I'm running into a strange issue.

I created a new java project with the following dependencies in my build.gradle.kts:

```
implementation("com.hedera.hashgraph:sdk:2.28.0")
implementation("io.grpc:grpc-netty-shaded:1.56.1")
implementation("org.slf4j:slf4j-simple:2.0.7")
```

And this is what my code looks like.

```
var clientId = AccountId.fromString("0.0.xxx");
var clientPrivateKey = PrivateKey.fromString("xxx");
var client = Client.forMainnet();
client.setOperator(clientId, clientPrivateKey);
client.setDefaultMaxTransactionFee(new Hbar(5));
client.setDefaultMaxQueryPayment(new Hbar(5));
client.setLogger(new Logger(LogLevel.DEBUG));

var tokenId   = TokenId.fromString(String.format("0.0.%d", 731861)); //SAUCE
var ownerId   = AccountId.fromString(String.format("0.0.%d", 1234)); //update with your account id
var spenderId = AccountId.fromString(String.format("0.0.%d", 5678)); //update with your account id

System.out.println("Approving allowance for spender..");
    Thread.sleep(5000);

    var future = new AccountAllowanceApproveTransaction()
      .approveTokenAllowance(tokenId,
          ownerId,
          spenderId,
          123245)
      .executeAsync(client)
      .thenAccept(response -> {
        TransactionReceipt receipt;
        try {
          System.out.println("Executed. getting receipt..");
          receipt = response.getReceipt(client);
          System.out.println("Token approve allowance - status: " + receipt.status);
        } catch (ReceiptStatusException e) {
          System.out.println("Token approve allowance - receipt error: " + e.getMessage());
        } catch (Exception e) {
          System.out.println("Token approve allowance - error: " + e.getMessage());
        }
      })
      .exceptionally(ex -> {
        System.out.println("AccountAllowanceApproveTransaction error" + ex.getMessage());
        return null;
      });
    
      future.get();
      System.out.println("Done.");
```

This code runs fine when I debug it in `IntelliJ IDEA 2023.1.5 (Ultimate Edition)`. I get the following output

```
Approving allowance for spender..
Executed. getting receipt..
Token approve allowance - status: SUCCESS
Done.
```

All is well so far.

I then compiled a fat JAR using com.github.johnrengelman.shadow version 7.1.0 which bundles all up dependencies. 

However, when I run it via `java -jar <path to jar>` on Windows 10 or Linux it fails. This is my output:

```
Approving allowance for spender..
[hedera-sdk-8] WARN com.hedera.hashgraph.sdk.logger.Logger - Retrying in 8000 ms after channel connection failure with node 0.0.6 during attempt #1
[hedera-sdk-0] WARN com.hedera.hashgraph.sdk.logger.Logger - Retrying in 8000 ms after channel connection failure with node 0.0.8 during attempt #2
[hedera-sdk-8] WARN com.hedera.hashgraph.sdk.logger.Logger - Retrying in 8000 ms after channel connection failure with node 0.0.27 during attempt #3
[hedera-sdk-0] WARN com.hedera.hashgraph.sdk.logger.Logger - Retrying in 8000 ms after channel connection failure with node 0.0.10 during attempt #4
[hedera-sdk-8] WARN com.hedera.hashgraph.sdk.logger.Logger - Retrying in 8000 ms after channel connection failure with node 0.0.26 during attempt #5
[hedera-sdk-0] WARN com.hedera.hashgraph.sdk.logger.Logger - Retrying in 8000 ms after channel connection failure with node 0.0.14 during attempt #6
```

It just retries infinitely. 

### Steps to reproduce

builld.gradle.kts definition:

```
plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.hedera.hashgraph:sdk:2.28.0")
    implementation("io.grpc:grpc-netty-shaded:1.56.1")
    implementation("org.slf4j:slf4j-simple:2.0.7")
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>().configureEach {
    archiveBaseName.set("HederaTest")
    manifest {
        attributes["Main-Class"] = "org.example.Main" // Replace with your main class
    }
}

tasks.named("build").configure {
    dependsOn("shadowJar")
}

tasks.test {
    useJUnitPlatform()
}
```

Code:
```
package org.example;

import com.hedera.hashgraph.sdk.*;
import com.hedera.hashgraph.sdk.logger.LogLevel;
import com.hedera.hashgraph.sdk.logger.Logger;

import java.util.HashMap;
import java.util.concurrent.TimeoutException;

public class Main {
  public static void main(String[] args) throws ReceiptStatusException, PrecheckStatusException, TimeoutException, InterruptedException {

    try {

      var clientId = AccountId.fromString("0.0.xxxx"); //update
      var clientPrivateKey = PrivateKey.fromString("xxxx"); //update

      var client = Client.forMainnet();
      client.setLogger(new Logger(LogLevel.TRACE));
      client.setOperator(clientId, clientPrivateKey);
      client.setDefaultMaxTransactionFee(new Hbar(5));
      client.setDefaultMaxQueryPayment(new Hbar(5));

      var tokenId = TokenId.fromString(String.format("0.0.%d", 731861));
      var ownerId = AccountId.fromString(String.format("0.0.%d", 1234)); //update
      var spenderId = AccountId.fromString(String.format("0.0.%d", 5678)); //update

      System.out.println("Approving allowance for spender..");

      var future = new AccountAllowanceApproveTransaction()
        .approveTokenAllowance(tokenId,
            ownerId,
            spenderId,
            123245)
        .executeAsync(client)
        .thenAccept(response -> {
          TransactionReceipt receipt;
          try {
            System.out.println("Executed. getting receipt..");
            receipt = response.getReceipt(client);
            System.out.println("Token approve allowance - status: " + receipt.status);
          } catch (ReceiptStatusException e) {
            System.out.println("Token approve allowance - receipt error: " + e.getMessage());
          } catch (Exception e) {
            System.out.println("Token approve allowance - error: " + e.getMessage());
          }
        })
        .exceptionally(ex -> {
          System.out.println("AccountAllowanceApproveTransaction error" + ex.getMessage());
          return null;
        });

      future.get();
      System.out.println("Done.");
    }
    catch (Exception e) {
      System.out.println("Exception: " + e.getMessage());
    }
  }
}
```

run `./gradlew clean build`

Then run `java -jar HederaTest-1.0-SNAPSHOT-all.jar`

### Hedera network

mainnet

### Version

2.28.0

### Operating system

Windows

**Comment by iron4548** [comment]
Furthermore, if I add:

`implementation("com.google.protobuf:protobuf-java:3.21.8") to build.gradle.kts`

I get this error which may or may not be related to the issue above:

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/hedera/hashgraph/sdk/proto/NftAllowance.mergeApprovedForAll(Lcom/google/protobuf/BoolValue;)V @31: invokevirtual
  Reason:
    Type 'com/google/protobuf/BoolValue' (current frame, stack[2]) is not assignable to 'com/google/protobuf/GeneratedMessageLite'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'com/hedera/hashgraph/sdk/proto/NftAllowance', 'com/google/protobuf/BoolValue' }
    stack: { 'com/hedera/hashgraph/sdk/proto/NftAllowance', 'com/google/protobuf/BoolValue$Builder', 'com/google/protobuf/BoolValue' }
  Bytecode:
    0000000: 2bb6 001f 572a b400 69c6 0028 2ab4 0069
    0000010: b800 6da5 001e 2a2a b400 69b8 0072 2bb6
    0000020: 0075 c000 76b6 0078 c000 6eb5 0069 a700
    0000030: 082a 2bb5 0069 b1                      
  Stackmap Table:
    same_frame(@49)
    same_frame(@54)

	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.google.protobuf.GeneratedMessageLite.getDefaultInstance(GeneratedMessageLite.java:389)
	at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:58)
	at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:144)
	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:56)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:91)
	at com.google.protobuf.MessageSchema.getMessageFieldSchema(MessageSchema.java:4852)
	at com.google.protobuf.MessageSchema.getSerializedSizeProto3(MessageSchema.java:2186)
	at com.google.protobuf.MessageSchema.getSerializedSize(MessageSchema.java:1461)
	at com.google.protobuf.GeneratedMessageLite.computeSerializedSize(GeneratedMessageLite.java:370)
	at com.google.protobuf.GeneratedMessageLite.getSerializedSize(GeneratedMessageLite.java:353)
	at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:882)
	at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:670)
	at com.google.protobuf.SchemaUtil.computeSizeMessage(SchemaUtil.java:675)
	at com.google.protobuf.MessageSchema.getSerializedSizeProto3(MessageSchema.java:2506)
	at com.google.protobuf.MessageSchema.getSerializedSize(MessageSchema.java:1461)
	at com.google.protobuf.GeneratedMessageLite.computeSerializedSize(GeneratedMessageLite.java:367)
	at com.google.protobuf.GeneratedMessageLite.getSerializedSize(GeneratedMessageLite.java:353)
	at com.google.protobuf.GeneratedMessageLite.getSerializedSize(GeneratedMessageLite.java:362)
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:58)
	at com.hedera.hashgraph.sdk.Transaction.wipeTransactionLists(Transaction.java:1128)
	at com.hedera.hashgraph.sdk.Transaction.freezeWith(Transaction.java:1060)
	at com.hedera.hashgraph.sdk.Transaction.onExecute(Transaction.java:1245)
	at com.hedera.hashgraph.sdk.Transaction.onExecuteAsync(Transaction.java:1269)
	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:490)
	at com.hedera.hashgraph.sdk.Transaction.executeAsync(Transaction.java:54)
	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:475)
	at com.hedera.hashgraph.sdk.Transaction.executeAsync(Transaction.java:54)
	at org.example.Main.main(Main.java:71)
```

**Comment by Petyo-Lukanov** [comment]
Thank you very much for creating this issue! We will prioritise it and make sure to follow up soon!

**Comment by thenswan** [comment]
Hey @iron4548, I reviewed your issue, and it did reproduce on my side as well. Here is the updated `build.gradle.kts`:
```
plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.hedera.hashgraph:sdk:2.28.0")
    implementation("io.grpc:grpc-netty-shaded:1.56.1")
    implementation("org.slf4j:slf4j-simple:2.0.7")
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>().configureEach {
    group = "shadow"
    from(sourceSets.main.get().output)
    mergeServiceFiles()

    // Defer the resolution  of 'runtimeClasspath'. This is an issue in the shadow
    // plugin that it automatically accesses the files in 'runtimeClasspath' while
    // Gradle is building the task graph. The three lines below work around that.
    inputs.files(project.configurations.runtimeClasspath)
    configurations = emptyList()
    doFirst { configurations = listOf(project.configurations.runtimeClasspath.get()) }

    archiveBaseName.set("HederaTest")
    manifest {
        attributes["Main-Class"] = "org.example.Main" // Replace with your main class
    }
}

tasks.named("build").configure {
    dependsOn("shadowJar")
}

tasks.test {
    useJUnitPlatform()
}
```

As you can see, I updated `tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>().configureEach` with logic from [here](https://github.com/hashgraph/hedera-services/blob/develop/build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.shadow-jar.gradle.kts) (its a Hedera shadow-jar gradle project plugin).

---

Regarding dependencies setup -- you did that correctly in `build.gradle.kts` that you provided, and there is no need to include `com.google.protobuf` dependencies.


Please let me know if it helped.

**Comment by iron4548** [comment]
Thank you!!! That ShadowJar workaround worked like a charm.

I'll go ahead and close this. This workaround will certainly be handy for those who are wanting to use Hedera's Java SDK.

**Comment by thenswan** [comment]
Awesome @iron4548, glad it helped 🙂 🙌

**Comment by iron4548** [comment]
@thenswan 

There's one more issue that I need some help with and may be related to what you're doing.

If I include the following two libraries in my Java project I get a 'Bad type on operand stack' when I try and approve allowance. If I exclude the hedera-protobuf-java-api library, then things will work fine. The protobuf-java-api library is included in a Java SDK that I'd like to include in addition to SDK that I'm using and that's where my problem started.

```java
implementation("com.hedera.hashgraph:sdk:2.28.0")
implementation("com.hedera.hashgraph:hedera-protobuf-java-api:0.42.0") //tried 0.40 and 0.43 too.
```

I guess they're not compatible?. How do one work around this? Thanks in advance.

**Comment by thenswan** [comment]
Hey @iron4548, please refer to [this guide](https://github.com/hashgraph/hedera-sdk-java/blob/bf64f1d63cb4979af436ad8cda4eda84b9fb9ae3/docs/java-app/java-app-quickstart.md) (note that its on temp branch) for info on how to set up Java project using the Hedera Java SDK.

Also, please let me know why you need `hedera-protobuf-java-api`.

**Comment by iron4548** [comment]
> Hey @iron4548, please refer to [this guide](https://github.com/hashgraph/hedera-sdk-java/blob/bf64f1d63cb4979af436ad8cda4eda84b9fb9ae3/docs/java-app/java-app-quickstart.md) (note that its on temp branch) for info on how to set up Java project using the Hedera Java SDK.

Thanks, that written guide looks really good. It will certainly get devs up and running using Java.

> Also, please let me know why you need `hedera-protobuf-java-api`.

Ah, it's for a side project that I'm working on. I was experimenting with custom-built mirror node provider and I was waiting to use the existing 'hedera-mirror-common' SDK library, and that requires `hedera-protobuf-java-api`. And having both `hedera-protobuf-java-api` and `com.hedera.hashgraph:sdk` for my Java project caused issues. It's an edge case so not a problem if they are not meant to co-exist with each other.

**Comment by thenswan** [comment]
@iron4548 for now, `hedera-protobuf-java-api` and `com.hedera.hashgraph:sdk` are not meant to co-exist with each other, and we will try to investigate when will have the capacity

**Comment by iron4548** [comment]
> @iron4548 for now, `hedera-protobuf-java-api` and `com.hedera.hashgraph:sdk` are not meant to co-exist with each other, and we will try to investigate when will have the capacity

Thanks for the confirmation that they are not meant to co-exist together. I wasn't sure if they could or not. I will find a different solution for now. Again this is an edge case and it's not important. If enough devs ask for it then maybe it will be worth the time to look into it.
