### ISSUE TITLE
driod API 33, ContractFunctionResult using Stream ?   tripping up.    java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream

### ISSUE THREAD

**Issue by johnda98** [hashgraph/hedera-sdk-java#1833]
### Description

yeah.. kinda at a Client  impasse now @Datadamus  as unable to use HH SDK to read the Wallet Users profile SC and Query and Execution seem to use Stream dependency and it seems to not get sucked into emulator runtime  yet compile build is fine.

"   ContractFunctionResult result_1 = new ContractCallQuery()
                .setGas(30000)
                .setContractId(existing)
                .setFunction("getfname")
              //   .setMaxQueryPayment(new Hbar(1))
                .execute(USER_ACCOUNT);"

digging deeper ..  droid studio, 1.8 compat, compiling for API33.. droid 13..  HH SDK and gRPC is checked - as per github for droid..ok

droid does support java 8 from version 7 Nougat and Stream was in 8.  .  noted API26 hedera SDK min.

ContractFunctionResult using Stream ?    Studio config looks ok.   later in thread - copy of gradles.

Process: com.mvp.olarawallet, PID: 10463
                                                                                                    java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractFunctionResult.<init>(ContractFunctionResult.java:152)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractCallQuery.mapResponse(ContractCallQuery.java:246)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractCallQuery.mapResponse(ContractCallQuery.java:48)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable$GrpcRequest.mapResponse(Executable.java:929)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:463)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:364)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.mvp.olarawallet.HederaServices.getacontract(HederaServices.java:357)
                                                                                                    	at com.mvp.olarawallet.MainActivity$LogonThread.run(MainActivity.java:251)
2024-06-02 11:29:15.501 10463-10497 Process                 com.mvp.olarawallet                  I  Sending signal. PID: 10463 SIG: 9

  ContractFunctionResult result_1 = new ContractCallQuery()
                .setGas(5000000)
                .setContractId(ContractId.fromString(existingcontractid))
                .setFunction("getfname")
                 .setMaxQueryPayment(new Hbar(5))
                .execute(USER_ACCOUNT);

        if (result_1.errorMessage!= null) {
            System.out.println("Error calling Contract " + result_1.errorMessage);
            return runitdetails;
        }

        String queryout = result_1.getString(0);

### Steps to reproduce

droid build. no probs

### Hedera network

testnet

### Version

sdk and gPRC as in the Hedera repo READme - for droid for java sdk

### Operating system

None

**Comment by johnda98** [comment]
stuffed big gas in there..  but its tripping up on result .. anyone help with this build ? all loosk to be correct to the repo's instructions.   Java 8 supported and all other project parms look ok.

**Comment by thenswan** [comment]
Hello @johnda98, thanks for submitting this issue 👍🏻  
We are aware of Android issues (like this one) and investigating them currently 👀

**Comment by johnda98** [comment]
yeah I'm setup for API 33 - google playstore minimum.

                                                                                                    java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.art/javalib/core-oj.jar)

the HH SDK uses Stream

![Uploading Screen Shot 2024-06-05 at 10.44.16 PM.png…]()

**Comment by johnda98** [comment]
<img width="1299" alt="Screen Shot 2024-06-05 at 10 46 27 PM" src="https://github.com/hashgraph/hedera-sdk-java/assets/13384285/30e99611-2437-45fc-b805-3545f648e3ec">

yep. checked.. I have src and comp as V8 ... but I guess it doesnt pull in the depdencies correctly .. yep droid 7  for API 25 24 is supposed to support V8 .. my build is min 33 and hits 34 so way above HH minimum API

**Comment by johnda98** [comment]
> Hello @johnda98, thanks for submitting this issue 👍🏻 We are aware of Android issues (like this one) and investigating them currently 👀

I upgraded the gRPC and HHSDK to latest - up and above whats ont he README for droid on the Java SDK from HH

Also pulled in Jetbrains JDK .. have the 1.8 source & compile set in gradle..  all seems to be coolio this end.. and at runtime still get the same .Stream  puke saying its not there in the build.

complex IDE for sure... and the gradle plugin syncs etc.

well. let me know if your core teams findings can shed any light -thanks.

**Comment by johnda98** [comment]
plugins {
    id 'com.android.application'
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.mvp.olarawallet"
        minSdk 33
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.mvp.olarawallet'

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'com.hedera.hashgraph:sdk:2.29.0'
    // okhttp transport (for lighter-weight applications or Android)
    implementation 'io.grpc:grpc-okhttp:1.58.0'
    // https://mvnrepository.com/artifact/io.github.cdimascio/dotenv-java
    implementation group: 'io.github.cdimascio', name: 'dotenv-java', version: '3.0.0'




and  proj level ...


// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '8.4.1' apply false
    id 'com.android.library' version '8.4.1' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by johnda98** [comment]
ok.. digging now.. RE: your ref - https://github.com/hashgraph/hedera-sdk-java/issues/1620

**Comment by johnda98** [comment]
I will step the build down to API27 - other threads says that resolves it.. but Google Play Store for production is min 33 ..soooooo... it needs sorting out.

**Comment by johnda98** [comment]
its as if the HH java SDK for droid.. as opposed to a Kotlin or a hybrid, has to chase  Google's API  playstore min API - now 33 - which may not like the Java Stream object
tried to back peddle to API27 - as a work around - since its a mvp and no need for a Playstore production listing - as of yet..

**Comment by johnda98** [comment]
yup.. checked all my Java17 dependencies in Studio and other gradle parms...   same deal on Stream on ContractCallQuery - which is on a Solidity string BTW..  maybe thats whats making it puke.. alot of gas - seems to accept 400M tbars then it pukes.



dont tell me I gotta not use .sol strings ? then SDK wont use Stream ?     @thenswan  :-)

 



java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractFunctionResult.<init>(ContractFunctionResult.java:152)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractCallQuery.mapResponse(ContractCallQuery.java:246)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractCallQuery.mapResponse(ContractCallQuery.java:48)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable$GrpcRequest.mapResponse(Executable.java:929)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:463)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:364)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.mvp.olarawallet.HederaServices.getacontract(HederaServices.java:383)
                                                                                                    	at com.mvp.olarawallet.MainActivity$LogonThread.run(MainActivity.java:250)

**Comment by thenswan** [comment]
Hey @johnda98, really appreciate your follow ups with new details.
We're actively working on supporting new hedera-services versions. Addressing the Android issue in the Java SDK is a priority for us as well and we will aim to shift our focus to this as soon as we can. I will follow up when it happens 👍🏻

**Comment by johnda98** [comment]
> Hey @johnda98, really appreciate your follow ups with new details. We're actively working on supporting new hedera-services versions. Addressing the Android issue in the Java SDK is a priority for us as well and we will aim to shift our focus to this as soon as we can. I will follow up when it happens 👍🏻

related ... https://github.com/flutter/flutter/issues/141949 

I'm removing the Sugar..  keep you updated.. and trying Abas's suggestions
