### ISSUE TITLE
io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-java#205]
The following message appears sporadically, and there is no clear methods on how to prevent it from happening.

Aug 21, 2019 10:31:39 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: ~~~ Channel ManagedChannelImpl{logId=221, target=0.testnet.hedera.com:50211} was not shutdown properly!!! ~~~
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:527)
        at com.hedera.hashgraph.sdk.Node.getChannel(Node.java:30)
        at com.hedera.hashgraph.sdk.QueryBuilder.getChannel(QueryBuilder.java:32)
        at com.hedera.hashgraph.sdk.HederaCall.newClientCall(HederaCall.java:34)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:43)
at AbapCallHandler.handleRequest(AbapCallHandler.java:588)
        at com.sap.conn.jco.rt.DefaultServerWorker$FunctionDispatcher.handleRequest(DefaultServerWorker.java:1047)
        at com.sap.conn.jco.rt.DefaultServerWorker$FunctionDispatcher.handleRequest(DefaultServerWorker.java:983)
        at com.sap.conn.jco.rt.DefaultServerWorker.dispatchRequest(DefaultServerWorker.java:147)
        at com.sap.conn.jco.rt.MiddlewareJavaRfc$JavaRfcServer.dispatchRequest(MiddlewareJavaRfc.java:3680)
        at com.sap.conn.jco.rt.MiddlewareJavaRfc$JavaRfcServer.listen(MiddlewareJavaRfc.java:2717)
        at com.sap.conn.jco.rt.DefaultServerWorker.dispatch(DefaultServerWorker.java:274)
        at com.sap.conn.jco.rt.DefaultServerWorker.loop(DefaultServerWorker.java:362)
        at com.sap.conn.jco.rt.DefaultServerWorker.run(DefaultServerWorker.java:231)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by abonander** [comment]
@JaimeSilver we've been seeing those errors in testing as well, as far as we can tell they're not fatal but we're still investigating on how to stop them occurring. Unfortunately that's a bit involved as it appears to be occurring in the gRPC lib itself.

**Comment by abonander** [comment]
Further discussion on #228 since it appears at the top of the issue list so hopefully no more duplicates are opened.
