### ISSUE TITLE
Not calling shutdown shows error message

### ISSUE THREAD

**Issue by cesaragv** [hashgraph/hedera-sdk-java#228]
Currently, hedera-sdk doesn't provide an option to close the client/transaction. Every time a `getAccountBalance` or a `FileUpdateTransaction` transaction is execute, we get the below error:

```
Sep 18, 2019 5:44:06 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=53, target=0.testnet.hedera.com:50211} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
at com.hedera.hashgraph.sdk.Node.getChannel(Node.java:30)
at com.hedera.hashgraph.sdk.QueryBuilder.getChannel(QueryBuilder.java:33)
at com.hedera.hashgraph.sdk.HederaCall.newClientCall(HederaCall.java:34)
at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:43)
at com.hedera.hashgraph.sdk.Client.getAccountBalance(Client.java:133)
at com.hedera.services.exchange.ExchangeRateTool.execute(ExchangeRateTool.java:76)
```

**Comment by abonander** [comment]
Working on adding an `AutoCloseable` implementation to `Client` so it can be used with try-with-resources.

**Comment by abonander** [comment]
To be clear, the issue here is letting `Client` get garbage-collected without closing the underlying gRPC channels. This error message exists to ensure users wait for the channels to finish existing calls before discarding them (and theoretically catch errors during shutdown but the only exception type documented is `InterruptedException` on `awaitTermination()`).

Reusing them per-transaction should be okay.

**Comment by abonander** [comment]
`Client.putNode` should also probably shutdown the channel of a node if it gets replaced.

**Comment by cesaragv** [comment]
@abonander `Client.putNode` just replaces the node and the replaced node will be garbaged collected. So the exception will be thrown anyway. 

Meanwhile, is there another way to wait for the channels to finish existing calls?

**Comment by abonander** [comment]
That's what I meant, it should call `.shutdown()` on the replaced node.

There's no other way right now but I'm working on the aforementioned fix.

**Comment by abonander** [comment]
Opened #229.
