### ISSUE TITLE
exact fee to create a smart contract

### ISSUE THREAD

**Issue by lubhub612** [hashgraph/hedera-sdk-java#238]
ContractCreateTransaction contractTx = new ContractCreateTransaction(client).setBytecodeFile(newFileId)
                .setAutoRenewPeriod(Duration.ofSeconds(7890000))
                .setGas(100000000)
                .setTransactionFee(1_000_000_000)
                .setConstructorParams(
                    CallParams.constructor()
                        .addString("hello from hedera!"));

            TransactionReceipt contractReceipt = contractTx.executeForReceipt();
            ContractId newContractId = contractReceipt.getContractId();
        Exception in thread "main" com.hedera.hashgraph.sdk.HederaException: INSUFFICIENT_TX_FEE
	at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
	at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:33)
	at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:190)
	at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:34)
	at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:43)
	at com.hedera.hashgraph.sdk.Transaction.executeAndWaitFor(Transaction.java:200)
	at com.hedera.hashgraph.sdk.Transaction.executeForReceipt(Transaction.java:262)
	at com.hedera.hashgraph.sdk.TransactionBuilder.executeForReceipt(TransactionBuilder.java:178)
	at myaughedtestnetclaim.myfirstsmartcontract.main(myfirstsmartcontract.java:76)
Next time I changed  the transaction fees 
ContractCreateTransaction contractTx = new ContractCreateTransaction(client).setBytecodeFile(newFileId)
                .setAutoRenewPeriod(Duration.ofSeconds(7890000))
                .setGas(100000000)
                .setTransactionFee(2_000_000_000)
                .setConstructorParams(
                    CallParams.constructor()
                        .addString("hello from hedera!"));

            TransactionReceipt contractReceipt = contractTx.executeForReceipt();
            ContractId newContractId = contractReceipt.getContractId();
         Shown error of  Exception in thread "main" com.hedera.hashgraph.sdk.HederaException:   INSUFFICIENT_PAYER_BALANCE
	at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
	at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:33)
	at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:190)
	at com.hedera.hashgraph.sdk.Transaction.mapResponse(Transaction.java:34)
	at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:43)       
error is same......
want to know what is the exeact transaction fees to create a smart contract on Hedera Hashgraph??
I follow all setps from Examples of hedera-sdk-java

**Comment by abonander** [comment]
The `HederaException` class encompasses all error codes from the network, if you look at the message the error is different: `HederaException:   INSUFFICIENT_PAYER_BALANCE`; this means there is insufficient HBAR in the account to cover the fee you set.
