### ISSUE TITLE
Hedera Hashgraph returning BUSY

### ISSUE THREAD

**Issue by bwonymph** [hashgraph/hedera-sdk-java#290]
After submitting 1000+ transactions in succession, HH starts returning HederaException: BUSY. Switched nodes (0.0.3 -> 0.0.4) and error still replicates. 
```
com.hedera.hashgraph.sdk.HederaException: BUSY
        at com.hedera.hashgraph.sdk.HederaException.throwIfExceptional(HederaException.java:38)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:211)
        at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:15)
        at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:43)
        at com.hedera.hashgraph.sdk.Transaction.lambda$executeForRecord$2(Transaction.java:277)
        at com.hedera.hashgraph.sdk.Transaction.executeAndWaitFor(Transaction.java:232)
        at com.hedera.hashgraph.sdk.Transaction.executeForRecord(Transaction.java:276)
        at com.hedera.hashgraph.sdk.TransactionBuilder.executeForRecord(TransactionBuilder.java:195)
        at com.armada.controller.ConsensusController.lambda$pushData$0(ConsensusController.java:69)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

If I space out transaction batches (batches of up to 1k), it usually goes through without error. But once sum reaches 3k+, error returns.

**Comment by abonander** [comment]
What version of the SDK are you using?

**Comment by bwonymph** [comment]
0.5.2, let me try 0.8.1

**Comment by abonander** [comment]
`BUSY` simply means you have hit the throttling limit of a single node: https://github.com/hashgraph/hedera-protobuf/blob/master/src/main/proto/ResponseCode.proto#L22

If you have a legitimate use case for sending thousands of transactions in succession, you can spread the load across the network by connecting to multiple nodes at once with the [`Client(Map<AccountId, String>)`](https://github.com/hashgraph/hedera-sdk-java/blob/master/src/main/java/com/hedera/hashgraph/sdk/Client.java#L70) constructor. All the nodes you can connect to are listed on the following page for mainnet: https://docs.hedera.com/docs/mainnet#section-mainnet-address-book

**Comment by abonander** [comment]
For testnet:

```java
final Client client = new Client(new AccountId(3), "0.testnet.hedera.com:50211")
    .putNode(new AccountId(4), "1.testnet.hedera.com:50211")
    .putNode(new AccountId(5), "2.testnet.hedera.com:50211")
    .putNode(new AccountId(6), "3.testnet.hedera.com:50211");
```
