### ISSUE TITLE
getRecord not working

### ISSUE THREAD

**Issue by JaimeSilver** [hashgraph/hedera-sdk-java#365]
getRecord is throwing an Exception in thread "main" java.lang.NoSuchFieldError: TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT.

This also affects getReceipt in Smart Contracts.

-> Run example CreateStatefulContract on TESTNET
```
Exception in thread "main" java.lang.NoSuchFieldError: TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT
	at com.hedera.hashgraph.sdk.Status.<clinit>(Status.java:115)
	at com.hedera.hashgraph.sdk.TransactionReceipt.<init>(TransactionReceipt.java:30)
	at com.hedera.hashgraph.sdk.HederaReceiptStatusException.throwIfExceptional(HederaReceiptStatusException.java:39)
	at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:280)
	at com.hedera.hashgraph.sdk.QueryBuilder.mapResponse(QueryBuilder.java:27)
	at com.hedera.hashgraph.sdk.HederaCall.lambda$execute$0(HederaCall.java:55)
	at com.hedera.hashgraph.sdk.Backoff.tryWhile(Backoff.java:37)
	at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:58)
	at com.hedera.hashgraph.sdk.QueryBuilder.execute(QueryBuilder.java:189)
	at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:44)
	at com.hedera.hashgraph.sdk.TransactionId.getReceipt(TransactionId.java:148)
	at com.hedera.hashgraph.sdk.TransactionId.waitForConsensus(TransactionId.java:113)
	at com.hedera.hashgraph.sdk.TransactionId.getRecord(TransactionId.java:170)
	at CreateTransfer.main(CreateTransfer.java:54)
```

**Comment by mehcode** [comment]
What is the transaction you are trying to execute? 

---

That exception just looks like a bug in how the error is hit. Not that `getRecord` isn't working.

**Comment by JaimeSilver** [comment]
Inside the CreateStatefulContract, there is a         TransactionReceipt contractReceipt = contractTxId.getReceipt(client); in line 80. That call generates an uncaught error.
Same process happens inside the Get Record, since the (waitForConsensus(client, null);)  includes a getReceipt that fails.

**Comment by JaimeSilver** [comment]
Try running the CreateStatefulContract of the examples.

**Comment by abonander** [comment]
@JaimeSilver are you trying to build the SDK locally? You should try `mvn clean install` in the SDK before running the example. That error suggests that the compiled bytecode of the generated `ResponseCodeEnum` class is out of date.

**Comment by JaimeSilver** [comment]
Yes. I have a local copy of the protobuf that needed update. All is working fine now.
