### ISSUE TITLE
Node replacement in client leads to error

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#399]
Following debugging with Johnda98 on Discord, replacing the list of nodes for an existing client

```
        Map<AccountId, String> nodes = new HashMap<AccountId, String>();
        nodes.put(new AccountId(3), "0.testnet.hedera.com:50211");
        nodes.put(new AccountId(4), "1.testnet.hedera.com:50211");
        Client client = new Client(nodes);

        nodes = new HashMap<AccountId, String>();
        nodes.put(new AccountId(5), "2.testnet.hedera.com:50211");
        nodes.put(new AccountId(6), "3.testnet.hedera.com:50211");
        client.replaceNodes(nodes);
        
        client.setOperator(OPERATOR_ID, OPERATOR_KEY);
```

results in 

```
Exception in thread "main" com.hedera.hashgraph.sdk.LocalValidationException: transaction builder failed local validation:
.setNodeAccountId() required
	at com.hedera.hashgraph.sdk.HederaCall.checkValidationErrors(HederaCall.java:108)
	at com.hedera.hashgraph.sdk.TransactionBuilder.localValidate(TransactionBuilder.java:134)
	at com.hedera.hashgraph.sdk.TransactionBuilder.build(TransactionBuilder.java:184)
	at com.hedera.hashgraph.sdk.TransactionBuilder.execute(TransactionBuilder.java:193)
	at com.hedera.hashgraph.sdk.TransactionBuilder.execute(TransactionBuilder.java:1)
	at com.hedera.hashgraph.sdk.HederaCall.execute(HederaCall.java:55)
	at com.hedera.hashgraph.sdk.examples.CreateAccount.main(CreateAccount.java:57)
```

Stepping through the code, Client.pickNode() returns a null.
The `nodes` variable contains a list of node account ids, but no IP addresses

```
{0.0.3=null, 0.0.4=null}
```

**Comment by Sheng-Long** [comment]
Fixed as of this commit: https://github.com/hashgraph/hedera-sdk-java/commit/e7f4fcb37e6dd2f55605eccbf7227c6bb5895fad
