### ISSUE TITLE
ok with 1.1.2 but 1.1.5 returns Duplicate methods

### ISSUE THREAD

**Issue by johnda98** [hashgraph/hedera-sdk-java#402]
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name "getSignatureCase" with signature "()LSignaturePair.SignatureCase;" in class file com/hedera/hashgraph/sdk/crypto/ed25519/Ed25519PublicKey
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at leveridgesystems.GetAccountBalance.<clinit>(GetAccountBalance.java:19)

**Comment by mehcode** [comment]
@johnda98 Please clear your local cache and try compiling again or use the SDK from maven.

**Comment by johnda98** [comment]
Ryan.. fairly sure I did a eclipse maven update when I switched ver in the pom ..  yes prob a maven directory clog up as it does
