### ISSUE TITLE
Error: NOT_FOUND: ID not found or not an HCS topic 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-java#415]
Error occurs running the following example, but not sure why the error appears as it prints the topic ID and continues to receive the topic messages from the mirror node. This error was not occurring previously. 

```
package com.hedera.hashgraph.sdk.examples;
import com.hedera.hashgraph.sdk.Client;
import com.hedera.hashgraph.sdk.HederaStatusException;
import com.hedera.hashgraph.sdk.TransactionId;
import com.hedera.hashgraph.sdk.account.AccountId;
import com.hedera.hashgraph.sdk.consensus.ConsensusMessageSubmitTransaction;
import com.hedera.hashgraph.sdk.consensus.ConsensusTopicCreateTransaction;
import com.hedera.hashgraph.sdk.consensus.ConsensusTopicId;
import com.hedera.hashgraph.sdk.crypto.ed25519.Ed25519PrivateKey;

import java.nio.charset.StandardCharsets;
import java.util.Objects;

import com.hedera.hashgraph.sdk.mirror.MirrorClient;
import com.hedera.hashgraph.sdk.mirror.MirrorConsensusTopicQuery;
import io.github.cdimascio.dotenv.Dotenv;

public final class consensusPubSub {

    private static final AccountId OPERATOR_ID = AccountId.fromString(Objects.requireNonNull(Dotenv.load().get("OPERATOR_ID")));
    private static final Ed25519PrivateKey OPERATOR_KEY = Ed25519PrivateKey.fromString(Objects.requireNonNull(Dotenv.load().get("OPERATOR_KEY")));

    private static final String MIRROR_NODE_ADDRESS = Objects.requireNonNull(Dotenv.load().get("MIRROR_NODE_ADDRESS"));

    private consensusPubSub() {
    }

    public static void main(String[] args) throws InterruptedException, HederaStatusException {
        final MirrorClient mirrorClient = new MirrorClient(MIRROR_NODE_ADDRESS);

        // `Client.forMainnet()` is provided for connecting to Hedera mainnet
        // `Client.forPreviewnet()` is provided for connecting to Hedera previewNet
        Client client = Client.forTestnet();

        // Defaults the operator account ID and key such that all generated transactions will be paid for
        // by this account and be signed by this key
        client.setOperator(OPERATOR_ID, OPERATOR_KEY);

        final TransactionId transactionId = new ConsensusTopicCreateTransaction()
                .execute(client);

        final ConsensusTopicId topicId = transactionId.getReceipt(client).getConsensusTopicId();
        System.out.println("New topic created: " + topicId);

        System.out.println("wait 10s to propagate to the mirror ...");

        Thread.sleep(10000);

        new MirrorConsensusTopicQuery()
                .setTopicId(topicId)
                .subscribe(mirrorClient, resp -> {
                            String messageAsString = new String(resp.message, StandardCharsets.UTF_8);

                            System.out.println(resp.consensusTimestamp + " received topic message: " + messageAsString);
                        },
                        // On gRPC error, print the stack trace
                        Throwable::printStackTrace);

        // keep the main thread from exiting because the listeners run on daemon threads
        // noinspection InfiniteLoopStatement

        for (int i = 0; ; i++) {
         new ConsensusMessageSubmitTransaction()
                .setTopicId(topicId)
                .setMessage("hello, HCS! ")
                .execute(client);

            System.out.println("sent topic message: hello, HCS! " + i);

            Thread.sleep(2500);
        }
    }
}
```

Output:

```
> Task :consensusPubSub.main()
New topic created: 0.0.11933
wait 10s to propagate to the mirror ...
sent topic message: hello, HCS! 0
io.grpc.StatusRuntimeException: NOT_FOUND: ID not found or not an HCS topic
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
sent topic message: hello, HCS! 1
sent topic message: hello, HCS! 2
sent topic message: hello, HCS! 3
sent topic message: hello, HCS! 4
sent topic message: hello, HCS! 5
sent topic message: hello, HCS! 6
sent topic message: hello, HCS! 7
sent topic message: hello, HCS! 8
sent topic message: hello, HCS! 9
```

**Comment by SimiHunjan** [comment]
I was using v1.2.0.

I installed master(v0.1.2) locally and still receiving same error.

![Screen Shot 2020-08-31 at 8 26 13 PM](https://user-images.githubusercontent.com/21989138/91791596-69d86f80-ebc8-11ea-9534-f47fae60a633.png)
