### ISSUE TITLE
KEY_NOT_SET Protobuf error while getting Token info

### ISSUE THREAD

**Issue by rahul-kothari** [hashgraph/hedera-sdk-java#429]
Using maven version v 2.0.1

Error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Key#fromProtobuf: unhandled key case: KEY_NOT_SET
	at com.hedera.hashgraph.sdk.WithExecute.execute(WithExecute.java:51)
	at com.hedera.hashgraph.sdk.WithExecute.execute(WithExecute.java:34)

Caused by: java.lang.IllegalStateException: Key#fromProtobuf: unhandled key case: KEY_NOT_SET
	at com.hedera.hashgraph.sdk.Key.fromProtobuf(Key.java:26)
	at com.hedera.hashgraph.sdk.TokenInfo.fromProtobuf(TokenInfo.java:158)
	at com.hedera.hashgraph.sdk.TokenInfoQuery.mapResponse(TokenInfoQuery.java:49)
	at com.hedera.hashgraph.sdk.TokenInfoQuery.mapResponse(TokenInfoQuery.java:13)
	at com.hedera.hashgraph.sdk.Executable.lambda$executeAsync$3(Executable.java:93)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at net.javacrumbs.futureconverter.guavacommon.GuavaFutureUtils$ListenableFutureBackedValueSourceFuture$1.onSuccess(GuavaFutureUtils.java:139)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:558)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:531)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Clearly a protobuf error.

Code:
```
var info = new TokenInfoQuery().setTokenId(tokenId).execute(client);
System.out.println(info);
```

@SimiHunjan

**Comment by danielakhterov** [comment]
I believe this is now fixed on master. Our current integration tests pass even when no key is set on a `TokenCreateTransaction`  https://github.com/hashgraph/hedera-sdk-java/blob/master/sdk/src/integrationTest/java/TokenInfoIntegrationTest.java#L82
