### ISSUE TITLE
.toString() method fails with error

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-java#591]
With SDK 2.0.5, running this code

```
public class DecodeBinary {
  public static void main (String[] args) throws DecoderException, InvalidProtocolBufferException {
    String binaryHex = "2ac2010a580a130a0b08d38f8f880610a09be91512041899e11c120218041880c2d72f22020878da01330a0418a5a1201210303030303030313632373633373731351a190a130a0b08d38f8f880610a09be91512041899e11c1001180112660a640a20603edaec5d1c974c92cb5bee7b011310c3b84b13dc048424cd6ef146d6a0d4a41a40b6a08f310ee29923e5868aac074468b2bde05da95a806e2f4a4f452177f129ca0abae7831e595b5beaa1c947e2cb71201642bab33fece5184b04547afc40850a";
    byte[] transactionBytes = Hex.decodeHex(binaryHex);

    Transaction transaction = Transaction.fromBytes(transactionBytes);

    System.out.println(transaction.getTransactionId());
    System.out.println(transaction.toString());
  }
}
```

results in

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/hedera/hashgraph/sdk/proto/ConsensusUpdateTopicTransactionBody.mergeMemo(Lcom/google/protobuf/StringValue;)V @31: invokevirtual
  Reason:
    Type 'com/google/protobuf/StringValue' (current frame, stack[2]) is not assignable to 'com/google/protobuf/GeneratedMessageLite'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'com/hedera/hashgraph/sdk/proto/ConsensusUpdateTopicTransactionBody', 'com/google/protobuf/StringValue' }
    stack: { 'com/hedera/hashgraph/sdk/proto/ConsensusUpdateTopicTransactionBody', 'com/google/protobuf/StringValue$Builder', 'com/google/protobuf/StringValue' }
  Bytecode:
    0000000: 2bb6 005c 572a b400 70c6 0028 2ab4 0070
    0000010: b800 74a5 001e 2a2a b400 70b8 0079 2bb6
    0000020: 007c c000 7db6 007f c000 75b5 0070 a700
    0000030: 082a 2bb5 0070 b1                      
  Stackmap Table:
    same_frame(@49)
    same_frame(@54)

	at com.hedera.hashgraph.sdk.proto.TransactionBody.getConsensusUpdateTopic(TransactionBody.java:1759)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.protobuf.GeneratedMessageLite.invokeOrDie(GeneratedMessageLite.java:1164)
	at com.google.protobuf.MessageLiteToString.reflectivePrintWithIndent(MessageLiteToString.java:155)
	at com.google.protobuf.MessageLiteToString.toString(MessageLiteToString.java:61)
	at com.google.protobuf.GeneratedMessageLite.toString(GeneratedMessageLite.java:103)
	at com.hedera.hashgraph.sdk.Transaction.toString(Transaction.java:862)
	at DecodeBinary.main(DecodeBinary.java:14)
```

**Comment by danielakhterov** [comment]
@gregscullard When did you generate those bytes? We've added a regression test on the current `main` and those bytes work fine.
